/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package jm.kotlin.protoc.fit.test

import FitFileDataKt

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    val x = FitFileDataKt
        .Dsl
        ._create(
            FitFileDataSchema.FitFileData.newBuilder()
        )
    println(App().greeting)
}
